export default [
    'fas fa-american-sign-language-interpreting',
    'fas fa-assistive-listening-systems',
    'fas fa-audio-description',
    'fas fa-blind',
    'fas fa-braille',
    'fas fa-closed-captioning',
    'fas fa-deaf',
    'fas fa-low-vision',
    'fas fa-phone-volume',
    'fas fa-question-circle',
    'fas fa-sign-language',
    'fas fa-tty',
    'fas fa-universal-access',
    'fas fa-wheelchair',
    'fab fa-accessible-icon',

    'fas fa-bell',
    'fas fa-bell-slash',
    'fas fa-exclamation',
    'fas fa-exclamation-circle',
    'fas fa-exclamation-triangle',

    'fas fa-cat',
    'fas fa-crow',
    'fas fa-dog',
    'fas fa-dove',
    'fas fa-dragon',
    'fas fa-feather',
    'fas fa-feather-alt',
    'fas fa-fish',
    'fas fa-frog',
];